title: Digital Identities and Existential Risks
author:
  name: Hannah Bittl
  email: hb22656@essex.ac.uk
description: > # this means to ignore newlines until "show_excerpts:"
  This website should offer you a step-by-step introduction to the topic of "Digital Identities and Existential Risks".
  It was created as part of a project for the course "Navigating the Digital World" at the University of Essex in the autumn semester 2022.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
